name: Cleanup
on:
  pull_request:
    types: [closed]
jobs:
  cleanup:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16'
    - name: npm install
      run: |
        npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}
        npm install
      env:
        CI: true
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Cleanup branch using theme-pipeline
      run: |
        npx theme-pipeline cleanup --shop-name "shop-1" -k ${{ secrets.API_KEY_SHOP_1 }} -p ${{ secrets.API_PASSWORD_SHOP_1 }} -b "${GITHUB_HEAD_REF##*/}"
        npx theme-pipeline cleanup --shop-name "shop-2" -k ${{ secrets.API_KEY_SHOP_2 }} -p ${{ secrets.API_PASSWORD_SHOP_2 }} -b "${GITHUB_HEAD_REF##*/}"
